import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { fetchAPI } from '../lib/api';
const Home: NextPage = ({ homepage }: any) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-3xl font-bold underline">
        {homepage.attributes.hero.title}
      </h1>
    </div>
  );
};

export async function getStaticProps() {
  const [homepageRes] = await Promise.all([
    fetchAPI('/homepage', {
      populate: {
        hero: '*',
      },
    }),
  ]);

  console.log(homepageRes.data);

  return {
    props: {
      homepage: homepageRes.data,
    },
    revalidate: 1,
  };
}

export default Home;
